name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.4.1
  - pip=22.0.3
  - mlflow=1.22.0
  - scikit-learn=1.0.2
  - matplotlib=3.5.1
  - pillow=9.0.1
  - pip:
      - wandb==0.12.10
