name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.3.5
  - pip=21.3.1
  - scikit-learn=1.0.2
  - matplotlib==3.5.1
  - plotly==5.5.0
  - pillow=8.1.2
  - mlflow=1.22.0
  - pip:
      - wandb==0.12.9
