name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow=1.22.0
  - ipython=7.21.0
  - notebook=6.4.8
  - jupyterlab=3.2.8
  - cookiecutter=1.7.3
  - hydra-core=1.1.1
  - matplotlib=3.5.1
  - pandas=1.3.5
  - git=2.30.2
  - pip=22.0.3
  - pip:
      - wandb==0.12.10
