name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - requests=2.24.0
  - pip=21.3.1
  - seaborn=0.11.2
  - pandas=1.2.3
  - scikit-learn=1.0.2
  - matplotlib==3.5.1
  - pillow=8.0.0
  - pip:
      - wandb==0.12.9