name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=22.0.3
  - requests=2.24.0
  - mlflow=1.22.0
  - scikit-learn=1.0.2
  - pip:
      - wandb==0.12.10
      - git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components
