name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  # Complete HERE
  - python=3.8
  - requests=2.24.0
  - pip=21.3.1
  - mlflow=1.22.0
  - hydra-core=1.1.1
  - pip:
      - wandb==0.12.9
