name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.2.8
  - seaborn=0.11.2
  - pandas=1.3.5
  - pip=21.3.1
  - pandas-profiling=3.1.0
  - pyarrow=6.0.1
  - ipywidgets=7.6.5
  - pip:
      - wandb==0.12.9